# Generated by Django 4.2.5 on 2023-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0002_farmers_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmers',
            old_name='second_name',
            new_name='username',
        ),
    ]
