# Generated by Django 4.2.5 on 2023-09-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0006_farmproduct_farmmarketing_harvest_maize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='Maize',
        ),
        migrations.DeleteModel(
            name='FarmMarketing',
        ),
        migrations.DeleteModel(
            name='FarmProduct',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
    ]
