# Generated by Django 4.2.5 on 2023-09-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0008_harvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maize_Variety', models.CharField(choices=[('01', 'H614'), ('02', 'H512'), ('03', 'H513'), ('04', 'DH02'), ('05', 'DH03'), ('06', 'DH04'), ('07', 'H624'), ('08', 'H621'), ('10', 'H617'), ('11', 'H614'), ('12', 'H615'), ('13', 'H621'), ('14', 'H614'), ('15', 'H515'), ('16', 'H513'), ('17', 'PHB 3253'), ('18', 'PHB 30M35')], default='H614', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_channel', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('marketing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('Maize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfarm.farmproduct')),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='Maize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gfarm.farmproduct'),
        ),
    ]
