# Generated by Django 4.2.5 on 2023-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0009_farmproduct_farmmarketing_harvest_maize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='Maize_Variety',
            field=models.CharField(choices=[('01', 'H614'), ('02', 'H512'), ('03', 'H513'), ('04', 'DH02'), ('05', 'DH03'), ('06', 'DH04'), ('07', 'H624'), ('08', 'H621'), ('10', 'H617'), ('11', 'H614'), ('12', 'H615'), ('13', 'H621'), ('14', 'H614'), ('15', 'H515'), ('16', 'H513'), ('17', 'PHB 3253'), ('18', 'PHB 30M35')], max_length=100),
        ),
    ]
