# Generated by Django 4.2.5 on 2023-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0011_alter_farmproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
