# Generated by Django 4.2.5 on 2023-09-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0012_alter_harvest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmmarketing',
            name='Maize',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='Maize',
        ),
        migrations.DeleteModel(
            name='FarmProduct',
        ),
    ]
