# Generated by Django 4.2.5 on 2023-09-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0015_farmproduct_harvest_farmmarketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='Maize_Variety',
            field=models.CharField(choices=[('01', 'H614'), ('02', 'H512'), ('03', 'H513'), ('04', 'DH02'), ('05', 'DH03'), ('06', 'DH04'), ('07', 'H624'), ('08', 'H621'), ('10', 'H617'), ('11', 'H614'), ('12', 'H615'), ('13', 'H621'), ('14', 'H614'), ('15', 'H515'), ('16', 'H513'), ('17', 'PHB 3253'), ('18', 'PHB 30M35')], max_length=100),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='Maize',
            field=models.ForeignKey(default='Maize_Variety', on_delete=django.db.models.deletion.CASCADE, to='gfarm.farmproduct'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='region',
            field=models.CharField(choices=[('Central', 'Central Region'), ('Coast', 'Coast Region'), ('Eastern', 'Eastern Region'), ('Nairobi', 'Nairobi Region'), ('North Eastern', 'North Eastern Region'), ('Nyanza', 'Nyanza Region'), ('Rift Valley', 'Rift Valley Region'), ('Western', 'Western Region')], default='Central Region', max_length=20),
        ),
    ]
