# Generated by Django 4.2.5 on 2023-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0016_alter_farmproduct_maize_variety_alter_harvest_maize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmarketing',
            name='county',
            field=models.CharField(choices=[('001', 'Mombasa'), ('002', 'Kwale'), ('003', 'Kilifi'), ('004', 'Tana River'), ('005', 'Lamu'), ('006', 'Taita-Taveta'), ('007', 'Garissa'), ('008', 'Wajir'), ('009', 'Mandera'), ('010', 'Marsabit'), ('011', 'Isiolo'), ('012', 'Meru'), ('013', 'Tharaka-Nithi'), ('014', 'Embu'), ('015', 'Kitui'), ('016', 'Machakos'), ('017', 'Makueni'), ('018', 'Nyandarua'), ('019', 'Nyeri'), ('020', 'Kirinyaga'), ('021', "Murang'a"), ('022', 'Kiambu'), ('023', 'Turkana'), ('024', 'West Pokot'), ('025', 'Samburu'), ('026', 'Trans-Nzoia'), ('027', 'Uasin Gishu'), ('028', 'Elgeyo-Marakwet'), ('029', 'Nandi'), ('030', 'Baringo'), ('031', 'Laikipia'), ('032', 'Nakuru'), ('033', 'Narok'), ('034', 'Kajiado'), ('035', 'Kericho'), ('036', 'Bomet'), ('037', 'Kakamega'), ('038', 'Vihiga'), ('039', 'Bungoma'), ('040', 'Busia'), ('041', 'Siaya'), ('042', 'Kisumu'), ('043', 'Homa Bay'), ('044', 'Migori'), ('045', 'Kisii'), ('046', 'Nyamira'), ('047', 'Nairobi')], default='mombasa', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmproduct',
            name='Maize_Variety',
            field=models.CharField(choices=[('h614', 'H614'), ('h512', 'H512'), ('h513', 'H513'), ('dh02', 'DH02'), ('dh03', 'DH03'), ('dh04', 'DH04'), ('h624', 'H624'), ('h621', 'H621'), ('h617', 'H617'), ('h614', 'H614'), ('h615', 'H615'), ('h621', 'H621'), ('h614', 'H614'), ('h51515', 'H515'), ('h513', 'H513'), ('hb 3253', 'PHB 3253'), ('phb 30M35', 'PHB 30M35')], max_length=100),
        ),
    ]
