# Generated by Django 4.2.5 on 2023-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0019_remove_farmmarketing_date_contact_captured_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deseases',
            new_name='Diseases_and_Pestes',
        ),
    ]
